# Site settings
title: Derek Chen
email: me@derekychen.com
url: http://www.derekychen.com
description: "Derek Chen - Software Developer, Engineer, Student"

# Encoding
encoding: utf-8

#Blog settings
paginate: 5
paginate_path: "/blog/:num/"

# Build settings
markdown: kramdown
permalink: pretty
